export const PRODUCT_DETAILS = [
  {
    name: "Red Dry Chillis",
    variants: [
      {
        name: "Sannam 334",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "40 Ft",
        loadingPort: { port: "Chennai", country: "India" },
        description: [
          { name: "Best" },
          { name: "Medium Best" },
          { name: "Deluxe" },
        ],
      },
      {
        name: "Teja S17",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "40 Ft",
        loadingPort: { port: "Chennai", country: "India" },
        description: [
          { name: "Best" },
          { name: "Medium Best" },
          { name: "Deluxe" },
        ],
      },
      {
        name: "Byadgi Chilli",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "40 Ft",
        loadingPort: { port: "Mangalore", country: "India" },
        description: [{ name: "Kaddi" }, { name: "Dabbi" }, { name: "Deluxe" }],
      },
      {
        name: "Ramnad Mundu chilli",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "40 Ft",
        loadingPort: { port: "Tuticorin", country: "India" },
        description: [{ name: "Ist grade" }, { name: "IInd grade" }],
      },
    ],
  },
  {
    name: "Turmeric",
    variants: [
      {
        name: "Erode Turmeric",
        typicalLoadability: "17 MT",
        typicalLoadabilityValue: 17,
        containerType: "20 Ft",
        loadingPort: { port: "Chennai", country: "India" },
        description: [{ name: "Sannam" }, { name: "Bold" }],
      },
      {
        name: "Nizamabad Turmeric",
        typicalLoadability: "17 MT",
        typicalLoadabilityValue: 17,
        containerType: "20 Ft",
        loadingPort: {
          port: "Chennai",
          country: "India",
          area: "Krishnapatnam",
        },
        description: [{ name: "Sannam" }, { name: "Bold" }],
      },
      {
        name: "Sangli Turmeric / Rajpuri Turmeric",
        typicalLoadability: "17 MT",
        typicalLoadabilityValue: 17,
        containerType: "20 Ft",
        loadingPort: { port: "Mumbai", country: "India" },
        description: [{ name: "Sannam" }, { name: "Bold" }],
      },
      {
        name: "Allepey Turmeric",
        typicalLoadability: "17 MT",
        typicalLoadabilityValue: 17,
        containerType: "20 Ft",
        loadingPort: { port: "Chennai", country: "India" },
        description: [{ name: "Whole Turmeric finger" }],
      },
    ],
  },
  {
    name: "Coriander",
    variants: [
      {
        name: "Single parrot",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Green colour" }],
      },
      {
        name: "Double parrot",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Green colour" }],
      },
      {
        name: "Eagle",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Medium green colour" }],
      },
      {
        name: "Scooter",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Medium green colour" }],
      },
      {
        name: "Badami",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Brown colour" }],
      },
    ],
  },
  {
    name: "Cumin ",
    variants: [
      {
        name: "European Quality cumin",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [
          { name: "CRE 101 - 99.5 % Purity" },
          { name: "CRE 102 - 99% Purity" },
          { name: "CRE 103 - 98% Purity" },
        ],
      },
      {
        name: "Gulf Quality cumin",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [
          { name: "CRE 104 - 99% Purity" },
          { name: "CRE 105 - 98% Purity" },
        ],
      },
      {
        name: "Singapore Quality cumin",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [
          { name: "CRE 106 - 99% Purity" },
          { name: "CRE 107 - 98% Purity" },
        ],
      },
    ],
  },
  {
    name: "Fennel",
    variants: [
      {
        name: "USA Quality Fennel",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "99.5" }, { name: "99%" }],
      },
      {
        name: "European Quality Fennel",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "99.5%" }, { name: "99% " }, { name: "98%" }],
      },
      {
        name: "Gulf Quality Fennel",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "99%" }, { name: "98" }, { name: "97" }],
      },
      {
        name: "Singapore quality Fennel",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "99%" }, { name: "98%" }, { name: "97%" }],
      },
    ],
  },
  {
    name: "Dried Ginger",
    variants: [
      {
        name: "Calicut Quality Dried Ginger",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "kochi", country: "India" },
        description: [
          { name: "Non-Bleached Garbled Calicut Dried Ginger(NGK)" },
          { name: "Non-Bleached Un-Garbled Calicut Dried Ginger(NUGK)" },
        ],
      },
      {
        name: "Cochin Quality Dried Ginger ",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: {
          port: "kochi",
          country: "India",
        },
        description: [
          { name: "Non-Bleached Garbled Cochin Dried Ginger(NGC)" },
          { name: "Non-Bleached Un-Garbled Cochin Dried Ginger(NUGC)" },
        ],
      },
      {
        name: "Sangli Turmeric / Rajpuri Turmeric",
        typicalLoadability: "17 MT",
        typicalLoadabilityValue: 17,
        containerType: "20 Ft",
        loadingPort: { port: "Mumbai", country: "India" },
        description: [{ name: "Sannam" }, { name: "Bold" }],
      },
      {
        name: "Allepey Turmeric",
        typicalLoadability: "17 MT",
        typicalLoadabilityValue: 17,
        containerType: "20 Ft",
        loadingPort: { port: "Chennai", country: "India" },
        description: [{ name: "Whole Turmeric finger" }],
      },
    ],
  },
  {
    name: "Coriander",
    variants: [
      {
        name: "Single parrot",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Green colour" }],
      },
      {
        name: "Double parrot",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Green colour" }],
      },
      {
        name: "Eagle",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Medium green colour" }],
      },
      {
        name: "Scooter",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Medium green colour" }],
      },
      {
        name: "Badami",
        typicalLoadability: "10 MT",
        typicalLoadabilityValue: 10,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [{ name: "Brown colour" }],
      },
    ],
  },
  {
    name: "Cumin ",
    variants: [
      {
        name: "European Quality cumin",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [
          { name: "CRE 101 - 99.5 % Purity" },
          { name: "CRE 102 - 99% Purity" },
          { name: "CRE 103 - 98% Purity" },
        ],
      },
      {
        name: "Gulf Quality cumin",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [
          { name: "CRE 104 - 99% Purity" },
          { name: "CRE 105 - 98% Purity" },
        ],
      },
      {
        name: "Singapore Quality cumin",
        typicalLoadability: "14 MT",
        typicalLoadabilityValue: 14,
        containerType: "20 Ft",
        loadingPort: { port: "Mundra", country: "India" },
        description: [
          { name: "CRE 106 - 99% Purity" },
          { name: "CRE 107 - 98% Purity" },
        ],
      },
    ],
  },
];
